name: Docker Hub Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # github.repository is <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t $IMAGE_NAME:$(date +%s) -t $IMAGE_NAME:latest

    - if: github.ref == 'refs/heads/master'
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
